language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-google-m2repository
before_install:
- yes | sdkmanager "platforms;android-27"

install:
- cd ${TRAVIS_BUILD_DIR}
# install latest LCOV (1.9 was failing for me) [1]

- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
- tar xf lcov_1.11.orig.tar.gz
- sudo make -C lcov-1.11/ install

# install lcov to coveralls conversion + upload tool
- gem install coveralls-lcov

before_script: 
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --zerocounters

script:
- "./gradlew test"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
notifications:
  slack:
    secure: lv9JBksxds2KxTezn/T6f2DSi/Fi/gtd3AKrhMEo6UZyE7VD6u5nJNek6WptTejcYnzBqKLaZ+EpFCg1RFCtiQWYJT3LmkH9X0xdBbYDYLJjlUvD6yw/zufiJdatRQGnNiC/5MreT3U559XANmcPbimV+iLihdFVqPamUxPHXvcZ1KGd94Suw8GHH1hfmIitiT43UckjS6fYmDTiJeM9f1ApPFEKMFhmdp7DMdptXa1MBczSMAKWrd9blDVX263xDVh1K+Jb+lhLLj7qSRhSUrRqWBlS127WJo0GkWSyeiDkWlL9J+oQgd5mXNRiUsYiFQcCZem4F1YnvoHXzic8zZjKOzZmakEOPcFPwSmY5aIIaUJ7rSUphUstUHtnmEiFEnQ1dEMMupEc4JITO8DTtIyQ+nk44k1mBwL7/ctywkU/Wu6xXf2NKGEuHk3bQ73Neop7d7s7ids7tdLtj6T/bCQGxF/WDzVQ8+0QNAqT/WKW0D3BPUKXj3QXdC8SyHO9DplVIdjR9WlMp7/Wap+jJbEP/d1gakJB89zov6bjkWs4menMjIMkobyFVWsuqippE1hNP5c2YkpjR82oLQX4UN8RzU6sgQZlENvb7E+Y9voqeTSLaJ3GWaqWaosi0p5DzPyA9F3FeSb/5JLOBQ+Ah418U1oH/QnGjCenNjLSSQk=
    
    after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info # filter out system and test code
- lcov --list coverage.info # debug before upload
#- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls.. for a private repo using a token
- coveralls-lcov  coverage.info #for open source 



